/* tslint:disable */
export const sampleCocktail = {
  "idDrink": "12188",
  "strDrink": "Sherry Eggnog",
  "strDrinkAlternate": null,
  "strDrinkES": null,
  "strDrinkDE": null,
  "strDrinkFR": null,
  "strDrinkZH-HANS": null,
  "strDrinkZH-HANT": null,
  "strTags": null,
  "strVideo": null,
  "strCategory": "Ordinary Drink",
  "strIBA": null,
  "strAlcoholic": "Alcoholic",
  "strGlass": "Collins glass",
  "strInstructions": "Shake sherry, powdered sugar, and egg with ice and strain into a collins glass. Fill with milk and stir. Sprinkle nutmeg on top and serve.",
  "strInstructionsES": null,
  "strInstructionsDE": "Sherry, Puderzucker und Ei mit Eis schütteln und in ein Collins-Glas abseihen. Mit Milch füllen und umrühren. Muskatnuss darüber streuen und servieren.",
  "strInstructionsFR": null,
  "strInstructionsZH-HANS": null,
  "strInstructionsZH-HANT": null,
  "strDrinkThumb": "https://www.thecocktaildb.com/images/media/drink/xwrpsv1478820541.jpg",
  "strIngredient1": "Sherry",
  "strIngredient2": "Powdered sugar",
  "strIngredient3": "Egg",
  "strIngredient4": "Milk",
  "strIngredient5": "Nutmeg",
  "strIngredient6": null,
  "strIngredient7": null,
  "strIngredient8": null,
  "strIngredient9": null,
  "strIngredient10": null,
  "strIngredient11": null,
  "strIngredient12": null,
  "strIngredient13": null,
  "strIngredient14": null,
  "strIngredient15": null,
  "strMeasure1": "2 oz cream ",
  "strMeasure2": "1 tsp ",
  "strMeasure3": "1 whole ",
  "strMeasure4": null,
  "strMeasure5": null,
  "strMeasure6": null,
  "strMeasure7": null,
  "strMeasure8": null,
  "strMeasure9": null,
  "strMeasure10": null,
  "strMeasure11": null,
  "strMeasure12": null,
  "strMeasure13": null,
  "strMeasure14": null,
  "strMeasure15": null,
  "strCreativeCommonsConfirmed": "No",
  "dateModified": "2016-11-10 23:29:01"
}
/* tslint:enable */
